---
- hosts: all
  become: true
  tasks:
  - name: Java JDK
    apt:
      pkg: openjdk-8-jdk
      state: present
  - name: install docker
    apt:
      pkg: docker.io
      state: present
  - name: start docker
    service:
      name: docker
      state: started
      enabled: true
  - name: jar file deploy in node
    command: sudo docker run -itd -p 8888:8888 mitranmukesh/my-test-apps:1.6
  handlers:
  - name: run update
    apt:
      update_cache: yes
...
